spring:
  profiles:
    active: local
server:
  contextPath: /dojo-madness
  port: 9000
api:
  endpoint: https://overwatch-api.net/
---
#db configuration
spring:
  profiles: local
  h2:
    console:
        enabled: true
        path: /h2
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
    testWhileIdle: true
    validationQuery: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy