INSERT INTO HERO  (HERO_ID, NAME, REAL_NAME, HEALTH, ARMOUR,  SHIELD) VALUES (1,'eric','eric nascimento', 200, 100, 100);
INSERT INTO HERO  (HERO_ID, NAME, REAL_NAME, HEALTH, ARMOUR,  SHIELD) VALUES (2,'bruno','bruno nascimento', 100, 100, 100);
INSERT INTO HERO  (HERO_ID, NAME, REAL_NAME, HEALTH, ARMOUR,  SHIELD) VALUES (3,'anton','anton nascimento', 50, 10, 10);
--
INSERT INTO ABILITY (ABILITY_ID, NAME, DESCRIPTION, IS_ULTIMATE, HERO_ID) VALUES (1, 'Biotic Rifle', 'Rifle',1 , 1);
INSERT INTO ABILITY (ABILITY_ID, NAME, DESCRIPTION, IS_ULTIMATE, HERO_ID) VALUES (2, 'Sleep Dart', 'Ana’s power.',1, 1);
INSERT INTO ABILITY (ABILITY_ID, NAME, DESCRIPTION, IS_ULTIMATE, HERO_ID) VALUES (3, 'Biotic Grenade', 'Ana tosses a bioticß', 1, 2);
INSERT INTO ABILITY (ABILITY_ID, NAME, DESCRIPTION, IS_ULTIMATE, HERO_ID) VALUES (4, 'Twitter Post', 'Ana tosses a bioticß', 1, 3);
